// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {route} from '../models';

export function AddRoute(arg1:route.Route):Promise<string>;

export function DeleteRoute(arg1:route.Route):Promise<string>;

export function EditRoute(arg1:route.Route,arg2:route.Route):Promise<string>;

export function ListRoutes():Promise<Array<route.Route>>;
