// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoute(arg1) {
  return window['go']['main']['App']['AddRoute'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['main']['App']['DeleteRoute'](arg1);
}

export function EditRoute(arg1, arg2) {
  return window['go']['main']['App']['EditRoute'](arg1, arg2);
}

export function ListRoutes() {
  return window['go']['main']['App']['ListRoutes']();
}
