// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { route } from '../models';

export function AddRoute(arg1: route.Route): Promise<void>;

export function DeleteRoute(arg1: route.Route): Promise<void>;

export function Greet(arg1: string): Promise<string>;

export function ListRoutes(): Promise<Array<route.Route>>;
